import { createElement } from 'lwc';
import Neighborhood_inspire_stories from 'c/neighborhood_inspire_stories';

describe('c-neighborhood-inspire-stories', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-neighborhood-inspire-stories', {
            is: Neighborhood_inspire_stories
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});