public with sharing class AccountDataController {
   // apex method to fetch account records from salesforce database 
//    @AuraEnabled
//    public static list<Account> fetchAccounts(){        
//            list<Account> lstAccount = new list<Account>();
//            for(Account con : [SELECT name,accountnumber,accountsource,active__c,phone FROM Account LIMIT 5000]){
//             lstAccount.add(con);
//            } 
//            return lstAccount;        
//    }
}