import { LightningElement } from 'lwc';
import imageBookingHotel from '@salesforce/resourceUrl/imageFooterBookingHotel'
export default class FooterBookingHotel extends LightningElement {
    images = [
        {
            class:"img-border img-border-top",
            img:imageBookingHotel+'/'+'title-footer.svg'
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-1.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-2.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-3.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-4.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-5.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-6.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-7.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-8.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-9.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-10.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-11.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-12.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-13.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-14.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-15.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-16.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-17.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-18.svg',
        },
        {
            class:"",
            img:imageBookingHotel+'/'+'footer-img-19.svg',
        },
        {
            class:"img-border img-border-bot",
            img:imageBookingHotel+'/'+'footer-img-20.svg',
        },
    ]
    imagesFollow=[
        {
            img:imageBookingHotel+'/'+'icon-fb.svg'
        },
        {
            img:imageBookingHotel+'/'+'icon-instagram.svg'
        },
        {
            img:imageBookingHotel+'/'+'icon-twitter.png'
        }
    ]
    imagesContent=[
        {
            img:imageBookingHotel+'/'+'content-footer-1.png'
        },
        {
            img:imageBookingHotel+'/'+'content-footer-2.png'
        },
        {
            img:imageBookingHotel+'/'+'content-footer-3.png'
        },
        {
            img:imageBookingHotel+'/'+'content-footer-4.png'
        }
    ]
}