import { createElement } from 'lwc';
import Custom_carousel_1_images from 'c/custom_carousel_1_images';

describe('c-custom-carousel-1-images', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-custom-carousel-1-images', {
            is: Custom_carousel_1_images
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});